### ISSUE TITLE
why not able to solve correctly?

### ISSUE THREAD

**Issue by joeyjiaojg** [aemmitt-ns/radius#14]
Hi,
Assume I have below program:
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

int main()
{
  char buf[5];

  memset(buf, 0, 5);

  if (!read(0, buf, 5))
    printf("read error\n");

  if (buf[0] == 'c')
    if (buf[1] == 'r')
      if (buf[2] == 'a')
        if (buf[3] == 's')
          if (buf[4] == 'h')
            abort();

  return 0;
}
```

I want radius2 to solve the stdio to crash.

Executing the program and output
```
radius2 -p crash -s stdin 128

  stdin : "crbsh\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"
```

why it's `crbsh` not `crash`?

Given -F flag also doesn't generate `crash`, the max string it can get is `cras`. Any idea?

**Comment by aemmitt-ns** [comment]
Yes unfortunately you have run into something I did that I thought made radius2 more intuitive, which is avoid `abort` by default. generally in ctf contexts avoiding `abort` is the way to go. it also avoids `exit` which can cause issues too. However there is a simple fix, simply set the breakpoint to be `sym.imp.abort` and you will get the right answer! 

```
*[main][~/radius/tests]$ radius2 -p crash -s stdin 128                 

  stdin : "crath\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"

*[main][~/radius/tests]$ radius2 -p crash -s stdin 128 -b sym.imp.abort

  stdin : "crash\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"
```

**Comment by aemmitt-ns** [comment]
both `abort` and `exit` eventually call the `exit` syscall on https://github.com/aemmitt-ns/radius/blob/main/radius/src/sims/syscall.rs#L326 which sets the state to inactive so it won't be represented in the results. I will change this, at least for the `-F` option as it is definitely not intuitive there

**Comment by joeyjiaojg** [comment]
Thanks
