### ISSUE TITLE
Bug creates overflow in processor.rs

### ISSUE THREAD

**Issue by GanbaruTobi** [aemmitt-ns/radius#15]
When trying to solve the challenge:
https://github.com/angr/angr-doc/blob/master/examples/defcon2019quals_veryandroidoso/ooo.defcon2019.quals.veryandroidoso.apk

My code:

https://gist.github.com/GanbaruTobi/a01b31216e7dfc2c2e795b092eb290ca

creates a panic:

thread 'main' panicked at 'attempt to add with overflow', radius/src/processor.rs:712:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/core/src/panicking.rs:48:5
   3: radius2::processor::Processor::fetch_instruction
             at ./radius/src/processor.rs:712:17
   4: radius2::processor::Processor::execute_instruction
             at ./radius/src/processor.rs:718:9
   5: radius2::processor::Processor::step
             at ./radius/src/processor.rs:742:13
   6: radius2::processor::Processor::run
             at ./radius/src/processor.rs:853:38
   7: radius2::radius::Radius::run_until
             at ./radius/src/radius.rs:467:9
   8: dex::main
             at ./examples/dex/src/main.rs:95:25
   9: core::ops::function::FnOnce::call_once
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by GanbaruTobi** [comment]
![grafik](https://user-images.githubusercontent.com/15239745/172940874-a0baf067-2370-4fcb-926e-761f33cd112e.png)

Is calling a native function possible in a dex/apk?

**Comment by aemmitt-ns** [comment]
>Is calling a native function possible in a dex/apk?

no not at the moment, though it is planned

Additionally there shouldn't be an overflow, i fixed that, however there is definitely something going wrong there. The DEX support is limited but `invoke-static` should work so I need to figure out why that pc address is wrong.

**Comment by GanbaruTobi** [comment]
![image](https://user-images.githubusercontent.com/15239745/173180447-d3816314-220a-4092-8515-d9c9e5493bd3.png)
The method is native. 

![image](https://user-images.githubusercontent.com/15239745/173180232-f3285a75-9b6f-499c-96f2-ebd21e639a9c.png)

Else, its the only Method having a void return type.

**Comment by aemmitt-ns** [comment]
Ok I see. I am looking at the challenge right now. Unfortunately the only way to do it currently would be to hook each of the native call invoke-static instructions and in those hooks create a new Radius instance loading "lib/armeabi-v7a/libnative-lib.so" (this has no vector instructions and should execute properly), then create a new `call_state` and run the right corresponding method with `call_function`. But this sucks and i would understand if you didn't want to do it that way. I will look into fixing this and making it all automatic (like in angr). that is my eventual goal

**Comment by aemmitt-ns** [comment]
Alternatively you could use r2frida, and initialize a state from a hook in the odex code. i am not sure what the native calls look like there but hopefully everything should "just work" . if you have a rooted device you can run `setprop dalvik.vm.dex2oat-flags -g` and recompile the challenge app with `pm compile ...` and the odex code will contain debug symbols making finding the right methods much easier.  let me know if you do this and are successful cuz that would be nice

**Comment by GanbaruTobi** [comment]
I have a device and will try your suggestions. But i remember having trouble with achieving a hook from my tries with ESILSolve (https://github.com/radareorg/esilsolve/issues/2). Having learned a bit more about the tools try again and will keep u updated.

**Comment by GanbaruTobi** [comment]
Sadly i cannot help. Facing the same problem as last time, that the user apps are never compiled to everything (or speed) on my device. When reviewing the odex it has only used "verify". Having a Poco X3 NFC, with LineageOS 19.1 (Android 12) and i tried also with LineageOS 18 (Android 11).
![grafik](https://user-images.githubusercontent.com/15239745/173207972-a0a0a385-f227-477a-88a8-04f1a582bc80.png)

**Comment by aemmitt-ns** [comment]
you cant run `pm compile -m everything ... ` ?

**Comment by GanbaruTobi** [comment]
If i run it, i get the message "success" and the generated base.odex is only compiled with verify, as u can see above. I also verified this with oatdump. Same for other profiles like everything-profile, speed, speed-profile, .... Actually I tried it last time with a friends phone, i think he has some newer google pixel and we had the same effect. The only phone we got it to work was a very old device, like Android 8 or 9. Sadly by all the searching i didn't find a solution for this for now.

**Comment by GanbaruTobi** [comment]
![image](https://user-images.githubusercontent.com/15239745/173208821-328549c6-55f4-4800-8115-b9ce45ee6a8e.png)
So that is how it looks for me. No addresses on the classes (if that is a thing) and no methods at all.
![image](https://user-images.githubusercontent.com/15239745/173208925-4bf35c3f-e1e4-4928-82a1-b133c9e8e9a1.png)
And thats what the odex contains as info

**Comment by aemmitt-ns** [comment]
damn thats annoying. yeah i think i originally did this on a pixel with android 9 so its not too surprising that it doesnt work anymore. you could try manually running dex2oat. that should definitely work

**Comment by GanbaruTobi** [comment]
When building with dex2oat by hand:
```
dex2oat --dex-file=base.apk --oat-location=base.odex --compiler-filter=everything --oat-file=base.odex --oat-location=
/data/app/~~IaM0efaCbBd3dTr8RviWrQ==/ooo.defcon2019.quals.veryandroidoso-7_uDuvMOjOvpysBQW-fCOw==/oat/arm64/base.odex
--classpath-dir=/data/app/~~IaM0efaCbBd3dTr8RviWrQ==/ooo.defcon2019.quals.veryandroidoso-7_uDuvMOjOvpysBQW-fCOw== --cl
ass-loader-context=PCL[]{PCL[/system/framework/android.test.base.jar]#PCL[/system/framework/org.apache.http.legacy.jar
]} --instruction-set-features=default -g --debuggable --runtime-arg -Xdeny-art-apex-data-files --runtime-arg -Xtarget-
sdk-version:26 --runtime-arg -Xhidden-api-policy:enabled --runtime-arg -Xms64m --runtime-arg -Xmx512m
```
I can verify the filter was "everything" and the file is huge and should contain alot. But r2frida is not able to catch up information:
![image](https://user-images.githubusercontent.com/15239745/173210066-203d275d-5d7b-4ac5-ac07-07eefa99ae65.png)

**Comment by GanbaruTobi** [comment]
pulling the odex to local i can see stuff with r2:
![image](https://user-images.githubusercontent.com/15239745/173210259-e542a873-ecc3-4e2b-99e4-d14bead7c72c.png)
![image](https://user-images.githubusercontent.com/15239745/173210262-18748e40-ce8f-42be-9e16-da929fb93028.png)
So maybe the odex formatting changed somewhat and r2frida is not catching this with :icm, but I am just guessing.

**Comment by aemmitt-ns** [comment]
hmm  the methods dont come up in r2frida with :is?

**Comment by GanbaruTobi** [comment]
Oh sorry (got quite early here), yes that works, but is missing the Solver.solve function in both r2frida and r2.
![image](https://user-images.githubusercontent.com/15239745/173213631-4832b7f8-bee4-491c-afb4-d18e49543cb1.png)
I will try my luck later to find it manually

**Comment by GanbaruTobi** [comment]
![image](https://user-images.githubusercontent.com/15239745/173213928-6b403fe2-c903-4603-a349-4853a9caea34.png)
I just also checked with oatdump, and it says to not have compiled all methods, so maybe the ~6000 line method was too much...

**Comment by aemmitt-ns** [comment]
yeah the native methods will still be in the native library, it wont pull those in. there are flags to set the max method size for dex2oat to compile though

**Comment by GanbaruTobi** [comment]
I wasn't suspecting it to pull the methods in, but was thinking that maybe the native library will be linked. Since I dont see how to achieve that with the given parameters of dex2oat (the lib would be in the base.apk). I played with the max method size (--large-method... --huge-method...) and other reasonable parameters without success. Also i think that the "everything" profile is realy made to use all possible. I think i will stop on this matter for now, but thanks so much for all the support

**Comment by GanbaruTobi** [comment]
I will just leave a more parameter rich try here for documentation purposes:
 `dex2oat64 --dex-file=base.apk --oat-location=base.odex --compiler-filter=everything --oat-file=base.odex --oat-location=/data/app/~~IaM0efaCbBd3dTr8RviWrQ==/ooo.defcon2019.quals.veryandroidoso-7_uDuvMOjOvpysBQW-fCOw==/oat/arm64/base.odex --classpath-dir=/data/app/~~IaM0efaCbBd3dTr8RviWrQ==/ooo.defcon2019.quals.veryandroidoso-7_uDuvMOjOvpysBQW-fCOw== --class-loader-context=PCL[]{PCL[/system/framework/android.test.base.jar]#PCL[/system/framework/org.apache.http.legacy.jar]} --instruction-set-features=default -g --debuggable --runtime-arg -Xdeny-art-apex-data-files --runtime-arg -Xtarget-sdk-version:26 --runtime-arg -Xhidden-api-policy:enabled --runtime-arg -Xms64m --runtime-arg -Xmx512m --runtime-arg -Xrelocate --android-root=/data/app/~~IaM0efaCbBd3dTr8RviWrQ==/ooo.defcon2019.quals.veryandroidoso-7_uDuvMOjOvpysBQW-fCOw== --huge-method-max=999999999 --large-method-max=999999999 --deduplicate-code=false --compact-dex-level=none`

**Comment by aemmitt-ns** [comment]
yes thank you for trying! i will try to get more dex code working and properly add native function calls so these kinds of workarounds arent necessary

**Comment by GanbaruTobi** [comment]
Since this Issue was for the bug in the processor.rs and this is resolved, I will close this
