### ISSUE TITLE
Trying EsCrackMe.apk with Frida

### ISSUE THREAD

**Issue by GanbaruTobi** [aemmitt-ns/radius#16]
When trying to recreate 
[how-to-perform-symbolic-execution-of-mobile-apps-with-r2frida-esilsolve]( https://www.nowsecure.com/blog/2021/03/10/how-to-perform-symbolic-execution-of-mobile-apps-with-r2frida-esilsolve/) i get the following base.odex representation:
![grafik](https://user-images.githubusercontent.com/15239745/174460682-8b9af5ec-af58-4027-8562-ee475f25d5ca.png)

From the video in the blog the code looks quite the same (so i suppose its not a radare issue):
![grafik](https://user-images.githubusercontent.com/15239745/174460753-12c83614-42e5-4453-87c7-ae2b066aab9c.png)

I try solving with the following code: https://gist.github.com/GanbaruTobi/1821f9c4cedbc98f07a2c15c22bfae5f

Expected result: 0xcafebabe
Got result: 0xbadd000c
The resulting flag is wrong: 
![grafik](https://user-images.githubusercontent.com/15239745/174460828-5ae4bf1a-30c2-47a9-a9d5-5efab00bf08a.png)

Besides, if u have an idea how to pull the address correctly for each attachment, we could at this to the repo (when its working correctly).

**Comment by GanbaruTobi** [comment]
Thats the execution:
0x6fa4eb3470    stp x0, x30, [sp, -0x10]!                |  16,sp,-=,x0,sp,=[8],x30,sp,8,+,=[8]
0x6fa4eb3474    nop                                      |  ,
0x6fa4eb3478    movz x16, 0xd                            |  13,x16,=
0x6fa4eb347c    movk x16, 0xbadd, lsl 16                 |  0xffffffff0000ffff,x16,&,3135045632,|,x16,=
0x6fa4eb3480    cmp x2, x16                              |  x16,x2,==,$z,zf,:=,63,$s,nf,:=,64,$b,!,cf,:=,63,$o,vf,:=
0x6fa4eb3484    cset w0, ne                              |  zf,!,?{,1,}{,0,},w0,=
0x6fa4eb3488    cneg w0, w0, lt                          |  nf,vf,^,?{,,}
0x6fa4eb348c    tbz w0, 0x1f, 0x6fa4eb34a0               |  31,1,<<,w0,&,!,?{,479508247712,pc,=,}

symbolic PC: (ite (= #x0000000000000000 (bvand (concat #x00000000 (ite (= flag #x00000000badd000d) #x00000000 #x00000001)) #x0000000080000000)) #x0000006fa4eb34a0 #x0000006fa4eb3490)

0x6fa4eb34a0    movz x5, 0x44                            |  68,x5,=
0x6fa4eb3490    nop                                      |  ,
0x6fa4eb34a4    movz x4, 0xdddd                          |  56797,x4,=
0x6fa4eb34a8    movk x4, 0xcccc, lsl 16                  |  0xffffffff0000ffff,x4,&,3435921408,|,x4,=
0x6fa4eb34ac    movz x3, 0xdead                          |  57005,x3,=
0x6fa4eb34b0    madd x0, x2, x5, x4                      |  x5,x2,*,x4,+,x0,=
0x6fa4eb34b4    mul x0, x0, x3                           |  x3,x0,*,x0,=
0x6fa4eb34b8    movz x16, 0xbeef                         |  48879,x16,=
0x6fa4eb34bc    movk x16, 0xbeef, lsl 16                 |  0xffffffff0000ffff,x16,&,3203334144,|,x16,=
0x6fa4eb34c0    movk x16, 0xbeef, lsl 32                 |  0xffff0000ffffffff,x16,&,209933706461184,|,x16,=
0x6fa4eb34c4    eor x0, x0, x16                          |  x16,x0,^,x0,=
0x6fa4eb34c8    movz x16, 0xb99e                         |  47518,x16,=
0x6fa4eb34cc    movk x16, 0xda86, lsl 16                 |  0xffffffff0000ffff,x16,&,3666214912,|,x16,=
0x6fa4eb34d0    movk x16, 0x261e, lsl 32                 |  0xffff0000ffffffff,x16,&,41910290874368,|,x16,=
0x6fa4eb34d4    movk x16, 0x2f, lsl 48                   |  0xffffffffffff,x16,&,13229323905400832,|,x16,=
0x6fa4eb3470    stp x0, x30, [sp, -0x10]!                |  16,sp,-=,x0,sp,=[8],x30,sp,8,+,=[8]
0x6fa4eb3474    nop                                      |  ,
0x6fa4eb3478    movz x16, 0xd                            |  13,x16,=
0x6fa4eb347c    movk x16, 0xbadd, lsl 16                 |  0xffffffff0000ffff,x16,&,3135045632,|,x16,=
0x6fa4eb3480    cmp x2, x16                              |  x16,x2,==,$z,zf,:=,63,$s,nf,:=,64,$b,!,cf,:=,63,$o,vf,:=
0x6fa4eb3484    cset w0, ne                              |  zf,!,?{,1,}{,0,},w0,=
0x6fa4eb3488    cneg w0, w0, lt                          |  nf,vf,^,?{,,}
0x6fa4eb348c    tbz w0, 0x1f, 0x6fa4eb34a0               |  31,1,<<,w0,&,!,?{,479508247712,pc,=,}

symbolic PC: (ite (= #x0000000000000000 (bvand (concat #x00000000 (ite (= flag #x00000000badd000d) #x00000000 #x00000001)) #x0000000080000000)) #x0000006fa4eb34a0 #x0000006fa4eb3490)

0x6fa4eb34a0    movz x5, 0x44                            |  68,x5,=
0x6fa4eb3490    nop                                      |  ,
0x6fa4eb34a4    movz x4, 0xdddd                          |  56797,x4,=
0x6fa4eb34a8    movk x4, 0xcccc, lsl 16                  |  0xffffffff0000ffff,x4,&,3435921408,|,x4,=
0x6fa4eb34ac    movz x3, 0xdead                          |  57005,x3,=
0x6fa4eb34b0    madd x0, x2, x5, x4                      |  x5,x2,*,x4,+,x0,=
0x6fa4eb34b4    mul x0, x0, x3                           |  x3,x0,*,x0,=
0x6fa4eb34b8    movz x16, 0xbeef                         |  48879,x16,=
0x6fa4eb34bc    movk x16, 0xbeef, lsl 16                 |  0xffffffff0000ffff,x16,&,3203334144,|,x16,=
0x6fa4eb34c0    movk x16, 0xbeef, lsl 32                 |  0xffff0000ffffffff,x16,&,209933706461184,|,x16,=
0x6fa4eb34c4    eor x0, x0, x16                          |  x16,x0,^,x0,=
0x6fa4eb34c8    movz x16, 0xb99e                         |  47518,x16,=
0x6fa4eb34cc    movk x16, 0xda86, lsl 16                 |  0xffffffff0000ffff,x16,&,3666214912,|,x16,=
0x6fa4eb34d0    movk x16, 0x261e, lsl 32                 |  0xffff0000ffffffff,x16,&,41910290874368,|,x16,=
0x6fa4eb34d4    movk x16, 0x2f, lsl 48                   |  0xffffffffffff,x16,&,13229323905400832,|,x16,=
0x6fa4eb34d8    cmp x0, x16                              |  x16,x0,==,$z,zf,:=,63,$s,nf,:=,64,$b,!,cf,:=,63,$o,vf,:=
0x6fa4eb34dc    cset w0, eq                              |  zf,?{,1,}{,0,},w0,=

**Comment by aemmitt-ns** [comment]
so the second check to make sure the value is correct gets turned into that `cset w0, eq` instruction, so all you need to do is add a couple lines before evaluating the flag that constrains `w0` to be 1 so `let w0 = new_state.registers.get("w0"); new_state.assert(w0.eq(&Value::Concrete(1, 0)));`

**Comment by aemmitt-ns** [comment]
let me know if this worked so i can close

**Comment by GanbaruTobi** [comment]
it worked, but do u have something in radius where a radare2 command can be executed to get an address? So to execute "s :il~foobar" for example? In that case i could make an example that gets the right address.

**Comment by aemmitt-ns** [comment]
yes you can execute any command with `radius.cmd(...)`. so something like "s \`:il~foobar\`; :is symname" should work. on phone right now ill check when im at my workstation
