### ISSUE TITLE
`brk` syscall implementation.

### ISSUE THREAD

**Issue by intrigus-lgtm** [aemmitt-ns/radius#2]
Hi, I have a question regarding this piece of code:
https://github.com/aemmitt-ns/radius/blob/1a6d76a9b04eb3f6913404e2c28ca7c39f87c813/radius/src/sims/syscall.rs#L235-L244

Is this part really implementing the `brk` syscall?
Isn't it instead implementing the **glibc** wrapper function?

Please have a look at the section "C library/kernel differences" in the man page:
https://man7.org/linux/man-pages/man2/brk.2.html

> However, the actual Linux system call returns the new
       program break on success.  On failure, the system call returns
       the current break.  The glibc wrapper function does some work
       (i.e., checks whether the new break is less than addr) to provide
       the 0 and -1 return values described above.

(I'm currently working on some kind of user-space emulator and also have to implement the `brk` and `sbrk` syscalls and I remembered your project from Twitter so I thought I'd look at how you implemented it :))

**Comment by aemmitt-ns** [comment]
Yes thank you it looks like you are right! This should be fixed with https://github.com/aemmitt-ns/radius/commit/4e5097cd1841c2657f67b48d56be3827c094cc5e but i definitely need to test syscall stuff more. Thanks for pointing this out
