### ISSUE TITLE
not support 128 bit?

### ISSUE THREAD

**Issue by joeyjiaojg** [aemmitt-ns/radius#6]
```
000000000001c8ec:  str x7, [sp, 0x128]                      |  x7,296,sp,+,DUP,tmp,=,=[8]
000000000001c8f0:  str **q0,** [sp, 0x70]                       |  q0,112,sp,+,DUP,tmp,=,=[16]
Unknown word: q0
thread '<unnamed>' panicked at 'attempt to shift right with overflow', /r2/radius/radius/src/memory.rs:595:47
```

I'm seeing this when run radius for aarch64.

**Comment by aemmitt-ns** [comment]
There is some support for instructions with 128 bit regs, and this ESIL expression should work but I need to make these values 128 bit when pushed to the stack. I will try to fix it now.

**Comment by aemmitt-ns** [comment]
Oh I didn't realize its not recognizing q0, thats weird. Which disassembler are you using? If you haven't changed it its either capstone 4 or 5. what output do you get from `r2 -c "aL~arm" -q -` ?

**Comment by aemmitt-ns** [comment]
Ok so in arm 64 r2 only has v0-31 but they should also be labeled with q0-31 . I will add them to the register profiles. This might work if you try the arm.v35 plugin by calling `radius.set_option("asm.arch", "arm.v35")`. But there are also some issues with the vector35 disassembly plugin also that I need to fix with a PR to r2.

**Comment by joeyjiaojg** [comment]
FYI anyway.

```
> e asm.arch
arm

[0x00006000]> aL~arm
a___  _16_32_64  arm.as      LGPL3   as ARM Assembler (use R2_ARM32_AS and R2_ARM64_AS environment)
adAe  _16_32_64  arm         BSD     Capstone v5 ARM disassembler
_dA_  _16_32_64  arm.gnu     GPL3    Acorn RISC Machine CPU
_dA_  _64        arm.v35     Apache  Vector35 ARM64 disassembler
_d__  _16_32     arm.winedbg LGPL2   WineDBG's ARM disassembler
```

**Comment by aemmitt-ns** [comment]
I am gonna close this as the `q*` register aliases have been added to r2 and expressions like the above will work now 

```
*[main][~/radius]$ radius2 -p /bin/ls -v -x 0x100003f00 -e '16,q0,=,q0,sp,=[16],sp,[16],.'
0x100003f00    0x00000000000000000000000000000010 "\u{10}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"

0x100003f00    pacibsp
```

However there are probably lots of instructions using the SIMD registers that will still not be quite right. I am going to open a new issue and try to better document these so they can be properly tackled.
